from __future__ import annotations

from datetime import date


TODAY = date(2026, 4, 28).isoformat()


def build_demo_state() -> dict:
    return {
        "meta": {
            "today": TODAY,
            "version": "0.1.0",
        },
        "projects": [
            {
                "id": "proj-phoenix",
                "name": "Phoenix B2B Portal",
                "owner": "赵敏",
                "status": "active",
                "priority": "high",
                "start_date": "2026-04-10",
                "target_launch_date": "2026-05-15",
                "health": "yellow",
                "risk_level": "medium",
                "latest_weekly_report": "",
            },
            {
                "id": "proj-atlas",
                "name": "Atlas Data Sync",
                "owner": "陈诚",
                "status": "active",
                "priority": "medium",
                "start_date": "2026-04-05",
                "target_launch_date": "2026-05-20",
                "health": "green",
                "risk_level": "low",
                "latest_weekly_report": "",
            },
            {
                "id": "proj-orbit",
                "name": "Orbit Metrics Revamp",
                "owner": "王兰",
                "status": "completed",
                "priority": "medium",
                "start_date": "2026-03-01",
                "target_launch_date": "2026-04-18",
                "health": "green",
                "risk_level": "low",
                "latest_weekly_report": "",
            },
        ],
        "tasks": [
            {
                "id": "task-a1",
                "project_id": "proj-phoenix",
                "milestone_id": "mile-p1",
                "name": "后端接口联调",
                "owner": "张三",
                "status": "in_progress",
                "priority": "high",
                "planned_start": "2026-04-18",
                "due_date": "2026-04-29",
                "last_updated": "2026-04-22",
                "estimated_hours": 12,
                "actual_hours": 6,
                "dependency_ids": [],
                "blocked_reason": "",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-a2",
                "project_id": "proj-phoenix",
                "milestone_id": "mile-p1",
                "name": "前端联调",
                "owner": "李四",
                "status": "not_started",
                "priority": "high",
                "planned_start": "2026-04-26",
                "due_date": "2026-04-30",
                "last_updated": "2026-04-26",
                "estimated_hours": 10,
                "actual_hours": 0,
                "dependency_ids": ["task-a1"],
                "blocked_reason": "依赖后端接口联调完成",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-a3",
                "project_id": "proj-phoenix",
                "milestone_id": "mile-p2",
                "name": "测试用例补齐",
                "owner": "王五",
                "status": "in_progress",
                "priority": "medium",
                "planned_start": "2026-04-24",
                "due_date": "2026-05-02",
                "last_updated": "2026-04-27",
                "estimated_hours": 8,
                "actual_hours": 3,
                "dependency_ids": [],
                "blocked_reason": "",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-b1",
                "project_id": "proj-atlas",
                "milestone_id": "mile-a1",
                "name": "数据映射梳理",
                "owner": "陈诚",
                "status": "in_progress",
                "priority": "high",
                "planned_start": "2026-04-16",
                "due_date": "2026-04-29",
                "last_updated": "2026-04-25",
                "estimated_hours": 7,
                "actual_hours": 5,
                "dependency_ids": [],
                "blocked_reason": "",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-b2",
                "project_id": "proj-atlas",
                "milestone_id": "mile-a1",
                "name": "增量同步脚本",
                "owner": "陈诚",
                "status": "in_progress",
                "priority": "high",
                "planned_start": "2026-04-20",
                "due_date": "2026-04-30",
                "last_updated": "2026-04-23",
                "estimated_hours": 9,
                "actual_hours": 5,
                "dependency_ids": [],
                "blocked_reason": "",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-b3",
                "project_id": "proj-atlas",
                "milestone_id": "mile-a1",
                "name": "联调验证",
                "owner": "周周",
                "status": "not_started",
                "priority": "medium",
                "planned_start": "2026-04-29",
                "due_date": "2026-05-02",
                "last_updated": "2026-04-27",
                "estimated_hours": 6,
                "actual_hours": 0,
                "dependency_ids": ["task-b2"],
                "blocked_reason": "等待增量同步脚本完成",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-c1",
                "project_id": "proj-orbit",
                "milestone_id": "mile-o1",
                "name": "指标字典整理",
                "owner": "孙可",
                "status": "done",
                "priority": "medium",
                "planned_start": "2026-03-10",
                "due_date": "2026-03-20",
                "last_updated": "2026-03-19",
                "estimated_hours": 5,
                "actual_hours": 6,
                "dependency_ids": [],
                "blocked_reason": "",
                "needs_follow_up": False,
                "risk_flag": False,
            },
            {
                "id": "task-c2",
                "project_id": "proj-orbit",
                "milestone_id": "mile-o1",
                "name": "埋点改造",
                "owner": "孙可",
                "status": "done",
                "priority": "high",
                "planned_start": "2026-03-15",
                "due_date": "2026-04-10",
                "last_updated": "2026-04-12",
                "estimated_hours": 10,
                "actual_hours": 14,
                "dependency_ids": [],
                "blocked_reason": "",
                "needs_follow_up": False,
                "risk_flag": False,
            },
        ],
        "milestones": [
            {
                "id": "mile-p1",
                "project_id": "proj-phoenix",
                "name": "联调完成",
                "owner": "赵敏",
                "planned_date": "2026-04-30",
                "actual_date": "",
                "status": "at_risk",
                "summary": "联调必须在月底完成，否则影响测试排期。",
            },
            {
                "id": "mile-p2",
                "project_id": "proj-phoenix",
                "name": "测试开始",
                "owner": "赵敏",
                "planned_date": "2026-05-03",
                "actual_date": "",
                "status": "pending",
                "summary": "测试阶段启动。",
            },
            {
                "id": "mile-a1",
                "project_id": "proj-atlas",
                "name": "同步链路打通",
                "owner": "陈诚",
                "planned_date": "2026-05-02",
                "actual_date": "",
                "status": "pending",
                "summary": "完成增量同步链路。",
            },
            {
                "id": "mile-o1",
                "project_id": "proj-orbit",
                "name": "改造上线",
                "owner": "王兰",
                "planned_date": "2026-04-18",
                "actual_date": "2026-04-21",
                "status": "done",
                "summary": "项目已交付。",
            },
        ],
        "risk_issues": [
            {
                "id": "risk-historical-1",
                "project_id": "proj-orbit",
                "title": "埋点改造需求二次变更",
                "type": "scope_change",
                "level": "medium",
                "reason": "产品需求冻结时间太晚，导致埋点口径返工。",
                "owner": "王兰",
                "status": "closed",
                "suggested_action": "下个项目提前完成指标口径冻结。",
                "should_escalate": False,
                "created_on": "2026-04-05",
            }
        ],
        "meeting_notes": [
            {
                "id": "meeting-p1",
                "project_id": "proj-phoenix",
                "title": "Phoenix 周例会",
                "meeting_date": "2026-04-27",
                "participants": ["赵敏", "张三", "李四", "产品经理-周岚"],
                "summary": "接口定义最近一周改动了两次，产品侧今天确认最终字段。",
                "decisions": ["接口字段 18:00 前确认最终版本"],
                "todos": ["产品确认字段", "后端同步接口文档"],
                "risk_signals": ["接口定义可能继续变更", "关键路径任务更新滞后"],
                "synced_to_risks": False,
            },
            {
                "id": "meeting-a1",
                "project_id": "proj-atlas",
                "title": "Atlas 同步专项会",
                "meeting_date": "2026-04-26",
                "participants": ["陈诚", "周周", "数据平台-刘洋"],
                "summary": "同步脚本还在处理中，暂未明确阻塞。",
                "decisions": ["本周优先完成同步链路"],
                "todos": ["陈诚补充进度说明"],
                "risk_signals": [],
                "synced_to_risks": True,
            },
        ],
        "weekly_reports": [],
        "follow_ups": [],
        "coordination_suggestions": [],
        "retrospectives": [],
        "agent_runs": [],
    }

